services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\ModuleBeta\Application\EventListener\AlphaFooEventListener:
        tags:
            - {
                name: kernel.event_listener,
                event: 'App\Shared\Application\Events\AlphaFooCreatedEvent',
                method: 'onAlphaFooCreated'
            }

